title:              Alex J. Chan
email:              alexjameschan@gmail.com
description:        Welcome to my website.
author:             Alex J. Chan
baseurl:            ""
url:                "https://alexjchan.com"

# Social Profiles
twitter_username:   AlexJChan
github_username:    XanderJC
facebook_username:  
instagram_username:  
linkedin_username: alexjchan

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
